-- Code generated by go generate ./internal/adapter/clickhouse/migrate/...; DO NOT EDIT.
-- Schema SoT: backend/internal/adapter/clickhouse/migrate (Ensure* / coldBootstrapStatements).
-- Regenerate: cd backend && go generate ./internal/adapter/clickhouse/migrate/...
-- Cold bootstrap only. Aggregates/MV are created by Ensure* at backend start.
-- Ops fallback when Ensure* cannot run: migrate_*.sql (also generated).

-- ============================================================
-- traffic_logs: основной поток событий МСЭ
-- ============================================================
CREATE TABLE IF NOT EXISTS traffic_logs
		(
			timestamp     DateTime64(3),
			parsed_at     DateTime64(3) DEFAULT now64(3),
			ingest_time   DateTime64(3) DEFAULT now64(3),
			vendor        LowCardinality(String) DEFAULT '',
			device        LowCardinality(String),
			src_ip        IPv4,
			dst_ip        IPv4,
			src_port      UInt32,
			dst_port      UInt32,
			action        LowCardinality(String),
			success       UInt8 MATERIALIZED
			              if(lower(action) IN ('accept','accepted','allow','allowed','built','close','decrypt','forward','inspect','mirror','monitor','nat','pass','permit','permitted','proxy','redirect','route','start','teardown','trust'), 1, 0),
			rule          String,
			proto         LowCardinality(String),
			src_zone      LowCardinality(String),
			dst_zone      LowCardinality(String),
			src_country   LowCardinality(String),
			dst_country   LowCardinality(String),
			src_city      LowCardinality(String) DEFAULT '',
			dst_city      LowCardinality(String) DEFAULT '',
			src_region    LowCardinality(String) DEFAULT '',
			dst_region    LowCardinality(String) DEFAULT '',
			src_lat       Float64 DEFAULT 0,
			src_lon       Float64 DEFAULT 0,
			dst_lat       Float64 DEFAULT 0,
			dst_lon       Float64 DEFAULT 0,
			bytes_sent    UInt64,
			bytes_recv    UInt64,
			packets_sent  UInt64,
			packets_recv  UInt64,
			INDEX idx_src_ip      src_ip      TYPE bloom_filter(0.01) GRANULARITY 4,
			INDEX idx_dst_ip      dst_ip      TYPE bloom_filter(0.01) GRANULARITY 4,
			INDEX idx_dst_port    dst_port    TYPE minmax              GRANULARITY 4,
			INDEX idx_action      action      TYPE set(0)              GRANULARITY 4
		)
		ENGINE = MergeTree()
		PARTITION BY toYYYYMMDD(timestamp)
		ORDER BY (toStartOfHour(timestamp), src_ip, dst_ip)
		TTL toDateTime(timestamp) + INTERVAL 30 DAY DELETE
		SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;

-- ============================================================
-- geo_ranges: GeoIP-база
-- ============================================================
CREATE TABLE IF NOT EXISTS geo_ranges
(
    start_ip UInt32,
    end_ip   UInt32,
    country  String,
    region   String,
    city     String,
    lat      Float64,
    lon      Float64
)
ENGINE = MergeTree()
ORDER BY (start_ip, end_ip);

-- ============================================================
-- enterprise_nets: подсети предприятия для аномалий
-- ============================================================
CREATE TABLE IF NOT EXISTS enterprise_nets
(
    start_ip   UInt32,
    end_ip     UInt32,
    network    String,
    label      String,
    country    String,
    region     String,
    city       String,
    created_at DateTime64(3),
    ver        UInt64,
    is_deleted UInt8 DEFAULT 0
)
ENGINE = ReplacingMergeTree(ver)
ORDER BY (start_ip, end_ip);

-- ============================================================
-- reputation_ranges: офлайн-репутационные списки
-- ============================================================
CREATE TABLE IF NOT EXISTS reputation_ranges
(
    list_name   LowCardinality(String),
    category    LowCardinality(String),
    start_ip    UInt32,
    end_ip      UInt32,
    source      LowCardinality(String),
    updated_at  DateTime64(3)
)
ENGINE = MergeTree()
ORDER BY (list_name, start_ip, end_ip);

-- ============================================================
-- parse_errors: строки логов, которые не удалось распарсить
-- ============================================================
CREATE TABLE IF NOT EXISTS parse_errors
(
    id        UUID DEFAULT generateUUIDv4(),
    timestamp DateTime64(3) DEFAULT now64(3),
    vendor    LowCardinality(String) DEFAULT '',
    reason    String,
    raw       String CODEC(ZSTD(3))
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY timestamp
TTL toDateTime(timestamp) + INTERVAL 7 DAY DELETE
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;

-- ============================================================
-- system_metrics: метрики самой системы
-- ============================================================
CREATE TABLE IF NOT EXISTS system_metrics
(
    timestamp     DateTime DEFAULT now(),
    metric_type   LowCardinality(String),
    target        LowCardinality(String),
    metric_name   LowCardinality(String),
    value         Float64,
    labels        String DEFAULT ''
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp, metric_type, target, metric_name)
TTL timestamp + INTERVAL 7 DAY DELETE
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;

-- ============================================================
-- v_metrics_latest: последние значения метрик
-- ============================================================
CREATE VIEW IF NOT EXISTS v_metrics_latest AS
SELECT
    metric_type, target, metric_name,
    argMax(value, timestamp) AS value,
    argMax(labels, timestamp) AS labels,
    max(timestamp) AS last_seen
FROM system_metrics
WHERE timestamp >= now() - INTERVAL 5 MINUTE
GROUP BY metric_type, target, metric_name;

-- ============================================================
-- dr_events: история backup/restore операций
-- ============================================================
CREATE TABLE IF NOT EXISTS dr_events
(
    timestamp DateTime64(3),
    actor     LowCardinality(String),
    action    LowCardinality(String),
    target    String,
    status    LowCardinality(String),
    message   String,
    meta      String
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp, action, target)
TTL toDateTime(timestamp) + INTERVAL 180 DAY DELETE
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;

-- ============================================================
-- audit_events: журнал admin/security действий
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_events
(
    timestamp     DateTime64(3),
    actor         LowCardinality(String),
    action        LowCardinality(String),
    resource_type LowCardinality(String),
    resource_id   String,
    result        LowCardinality(String),
    ip            String,
    details       String
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp, action, actor)
TTL toDateTime(timestamp) + INTERVAL 180 DAY DELETE
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;

-- ============================================================
-- anomaly_events: журнал аномалий карты
-- ============================================================
CREATE TABLE IF NOT EXISTS anomaly_events
(
    detected_at   DateTime64(3),
    window_start  DateTime64(3),
    window_end    DateTime64(3),
    code          LowCardinality(String),
    severity      LowCardinality(String),
    score         Float32,
    title         String,
    detail        String,
    src_ip        IPv4 DEFAULT toIPv4('0.0.0.0'),
    dst_ip        IPv4 DEFAULT toIPv4('0.0.0.0'),
    src_country   LowCardinality(String) DEFAULT '',
    dst_country   LowCardinality(String) DEFAULT '',
    src_city      LowCardinality(String) DEFAULT '',
    dst_city      LowCardinality(String) DEFAULT '',
    device        LowCardinality(String) DEFAULT '',
    event_count   UInt64,
    fingerprint   String,
    suppression_key String DEFAULT '',
    expires_at    DateTime64(3)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(detected_at)
ORDER BY (detected_at, code, fingerprint)
TTL toDateTime(detected_at) + INTERVAL 30 DAY DELETE
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;

-- ============================================================
-- anomaly_events suppression_key: ключ подавления повтора
-- ============================================================
ALTER TABLE anomaly_events ADD COLUMN IF NOT EXISTS suppression_key String DEFAULT '';

-- ============================================================
-- anomaly_acks: подтверждения аномалий
-- ============================================================
CREATE TABLE IF NOT EXISTS anomaly_acks
(
    fingerprint String,
    ack_at      DateTime64(3),
    ack_by      String
)
ENGINE = ReplacingMergeTree(ack_at)
ORDER BY fingerprint;

-- ============================================================
-- anomaly_suppressions: подавление повторов аномалий
-- ============================================================
CREATE TABLE IF NOT EXISTS anomaly_suppressions
(
    suppression_key   String,
    code              LowCardinality(String),
    source_fingerprint String,
    suppressed_at     DateTime64(3),
    suppressed_until  DateTime64(3),
    suppressed_by     String
)
ENGINE = ReplacingMergeTree(suppressed_at)
ORDER BY suppression_key
TTL toDateTime(suppressed_until) + INTERVAL 1 DAY DELETE;
