-- Code generated by go generate ./internal/adapter/clickhouse/migrate/...; DO NOT EDIT.
-- Schema SoT: backend/internal/adapter/clickhouse/migrate (Ensure* / coldBootstrapStatements).
-- Regenerate: cd backend && go generate ./internal/adapter/clickhouse/migrate/...
-- Updates traffic_logs.success MATERIALIZED to model.AllowedInClause().
-- Usually applied at backend start (EnsureTrafficLogsSuccess).
-- Manual:
--   docker compose exec -T clickhouse sh -c \
--     'clickhouse-client --password "$CLICKHOUSE_PASSWORD" --multiquery' \
--     < clickhouse/migrate_success.sql

ALTER TABLE traffic_logs
    MODIFY COLUMN success UInt8 MATERIALIZED
        if(lower(action) IN ('accept','accepted','allow','allowed','built','close','decrypt','forward','inspect','mirror','monitor','nat','pass','permit','permitted','proxy','redirect','route','start','teardown','trust'), 1, 0);
