-- Code generated by go generate ./internal/adapter/clickhouse/migrate/...; DO NOT EDIT.
-- Schema SoT: backend/internal/adapter/clickhouse/migrate (Ensure* / coldBootstrapStatements).
-- Regenerate: cd backend && go generate ./internal/adapter/clickhouse/migrate/...
-- Pre-aggregated map edges (IP daily + coords).
-- Runtime SoT: EnsureEdgesAggSchema. This file is a manual fallback.
-- Manual:
--   docker compose exec -T clickhouse sh -c \
--     'clickhouse-client --password "$CLICKHOUSE_PASSWORD" --multiquery' \
--     < clickhouse/migrate_edges_agg.sql
-- On an old volume prefer backend Ensure* (EXCHANGE + backfill).

CREATE TABLE IF NOT EXISTS traffic_edges_daily
		(
			day         Date,
			src_ip        IPv4,
			dst_ip        IPv4,
			cnt           SimpleAggregateFunction(sum, UInt64),
			blocked_cnt   SimpleAggregateFunction(sum, UInt64),
			allowed_cnt   SimpleAggregateFunction(sum, UInt64),
			bytes_sent    SimpleAggregateFunction(sum, UInt64),
			bytes_recv    SimpleAggregateFunction(sum, UInt64),
			packets_sent  SimpleAggregateFunction(sum, UInt64),
			packets_recv  SimpleAggregateFunction(sum, UInt64),
			src_lat_sum   SimpleAggregateFunction(sum, Float64),
			src_lon_sum   SimpleAggregateFunction(sum, Float64),
			dst_lat_sum   SimpleAggregateFunction(sum, Float64),
			dst_lon_sum   SimpleAggregateFunction(sum, Float64),
			coord_weight  SimpleAggregateFunction(sum, UInt64),
			last_action   AggregateFunction(argMax, String, DateTime64(3)),
			rule          AggregateFunction(any, String),
			proto         AggregateFunction(any, String),
			src_port      AggregateFunction(any, UInt32),
			dst_port      AggregateFunction(any, UInt32),
			device        AggregateFunction(any, String),
			src_zone      AggregateFunction(any, String),
			dst_zone      AggregateFunction(any, String),
			src_country   AggregateFunction(any, String),
			dst_country   AggregateFunction(any, String),
			src_city      AggregateFunction(any, String),
			dst_city      AggregateFunction(any, String)
		)
		ENGINE = AggregatingMergeTree()
		PARTITION BY day
		ORDER BY (day, src_ip, dst_ip)
		TTL day + INTERVAL 30 DAY DELETE
		SETTINGS ttl_only_drop_parts = 1;

CREATE MATERIALIZED VIEW IF NOT EXISTS traffic_edges_daily_mv
		TO traffic_edges_daily AS
		SELECT
			toDate(traffic_logs.timestamp) AS day,
			traffic_logs.src_ip AS src_ip,
			traffic_logs.dst_ip AS dst_ip,
			count() AS cnt,
			sum(if(lower(action) IN ('block','blocked','denied','deny','discard','discarded','drop','dropped','reject','rejected','reset'), toUInt64(1), toUInt64(0))) AS blocked_cnt,
			sum(if(lower(action) NOT IN ('block','blocked','denied','deny','discard','discarded','drop','dropped','reject','rejected','reset') AND lower(action) NOT IN ('','unknown'), toUInt64(1), toUInt64(0))) AS allowed_cnt,
			sum(traffic_logs.bytes_sent) AS bytes_sent,
			sum(traffic_logs.bytes_recv) AS bytes_recv,
			sum(traffic_logs.packets_sent) AS packets_sent,
			sum(traffic_logs.packets_recv) AS packets_recv,
			sumIf(traffic_logs.src_lat, (traffic_logs.src_lat != 0 OR traffic_logs.src_lon != 0) AND (traffic_logs.dst_lat != 0 OR traffic_logs.dst_lon != 0)) AS src_lat_sum,
			sumIf(traffic_logs.src_lon, (traffic_logs.src_lat != 0 OR traffic_logs.src_lon != 0) AND (traffic_logs.dst_lat != 0 OR traffic_logs.dst_lon != 0)) AS src_lon_sum,
			sumIf(traffic_logs.dst_lat, (traffic_logs.src_lat != 0 OR traffic_logs.src_lon != 0) AND (traffic_logs.dst_lat != 0 OR traffic_logs.dst_lon != 0)) AS dst_lat_sum,
			sumIf(traffic_logs.dst_lon, (traffic_logs.src_lat != 0 OR traffic_logs.src_lon != 0) AND (traffic_logs.dst_lat != 0 OR traffic_logs.dst_lon != 0)) AS dst_lon_sum,
			sum(if((traffic_logs.src_lat != 0 OR traffic_logs.src_lon != 0) AND (traffic_logs.dst_lat != 0 OR traffic_logs.dst_lon != 0), toUInt64(1), toUInt64(0))) AS coord_weight,
			argMaxState(traffic_logs.action, traffic_logs.timestamp) AS last_action,
			anyState(traffic_logs.rule) AS rule,
			anyState(traffic_logs.proto) AS proto,
			anyState(traffic_logs.src_port) AS src_port,
			anyState(traffic_logs.dst_port) AS dst_port,
			anyState(traffic_logs.device) AS device,
			anyState(traffic_logs.src_zone) AS src_zone,
			anyState(traffic_logs.dst_zone) AS dst_zone,
			anyState(traffic_logs.src_country) AS src_country,
			anyState(traffic_logs.dst_country) AS dst_country,
			anyState(traffic_logs.src_city) AS src_city,
			anyState(traffic_logs.dst_city) AS dst_city
		FROM traffic_logs
		GROUP BY day, src_ip, dst_ip;
