package migrate

import (
	"fmt"
	"strings"

	"geoatlas/internal/adapter/clickhouse/sqlclause"
)

const generatedSQLHeader = `-- Code generated by go generate ./internal/adapter/clickhouse/migrate/...; DO NOT EDIT.
-- Schema SoT: backend/internal/adapter/clickhouse/migrate (Ensure* / coldBootstrapStatements).
-- Regenerate: cd backend && go generate ./internal/adapter/clickhouse/migrate/...
`

// RenderColdBootstrapSQL — clickhouse/init.sql (cold bootstrap пустого тома).
func RenderColdBootstrapSQL() string {
	var b strings.Builder
	b.WriteString(generatedSQLHeader)
	b.WriteString("-- Cold bootstrap only. Aggregates/MV are created by Ensure* at backend start.\n")
	b.WriteString("-- Ops fallback when Ensure* cannot run: migrate_*.sql (also generated).\n")
	for _, stmt := range coldBootstrapStatements() {
		b.WriteString("\n-- ============================================================\n")
		b.WriteString("-- ")
		b.WriteString(stmt.title)
		b.WriteString("\n-- ============================================================\n")
		b.WriteString(withSemicolon(stmt.sql))
		b.WriteByte('\n')
	}
	return b.String()
}

// RenderMigrateSuccessSQL — ops fallback для EnsureTrafficLogsSuccess.
func RenderMigrateSuccessSQL() string {
	var b strings.Builder
	b.WriteString(generatedSQLHeader)
	b.WriteString("-- Updates traffic_logs.success MATERIALIZED to model.AllowedInClause().\n")
	b.WriteString("-- Usually applied at backend start (EnsureTrafficLogsSuccess).\n")
	b.WriteString("-- Manual:\n")
	b.WriteString("--   docker compose exec -T clickhouse sh -c \\\n")
	b.WriteString("--     'clickhouse-client --password \"$CLICKHOUSE_PASSWORD\" --multiquery' \\\n")
	b.WriteString("--     < clickhouse/migrate_success.sql\n\n")
	fmt.Fprintf(&b, `ALTER TABLE traffic_logs
    MODIFY COLUMN success UInt8 MATERIALIZED
        %s;
`, trafficLogsSuccessExpr())
	return b.String()
}

// RenderMigrateEdgesAggSQL — ops fallback для EnsureEdgesAggSchema (IP daily + MV).
func RenderMigrateEdgesAggSQL() string {
	var b strings.Builder
	b.WriteString(generatedSQLHeader)
	b.WriteString("-- Pre-aggregated map edges (IP daily + coords).\n")
	b.WriteString("-- Runtime SoT: EnsureEdgesAggSchema. This file is a manual fallback.\n")
	b.WriteString("-- Manual:\n")
	b.WriteString("--   docker compose exec -T clickhouse sh -c \\\n")
	b.WriteString("--     'clickhouse-client --password \"$CLICKHOUSE_PASSWORD\" --multiquery' \\\n")
	b.WriteString("--     < clickhouse/migrate_edges_agg.sql\n")
	b.WriteString("-- On an old volume prefer backend Ensure* (EXCHANGE + backfill).\n\n")
	table := injectIfNotExists(ipEdgesCreateTableSQL(
		sqlclause.IPEdgesDailyTable, "day", "Date", "day", ipEdgesDailyTTL,
	))
	mv := injectIfNotExists(ipEdgesCreateMVSQL(
		sqlclause.IPEdgesDailyMV, sqlclause.IPEdgesDailyTable,
		"toDate(traffic_logs.timestamp)", "day",
	))
	b.WriteString(withSemicolon(table))
	b.WriteByte('\n')
	b.WriteByte('\n')
	b.WriteString(withSemicolon(mv))
	b.WriteByte('\n')
	return b.String()
}

func injectIfNotExists(ddl string) string {
	ddl = strings.Replace(ddl, "CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", 1)
	ddl = strings.Replace(ddl, "CREATE MATERIALIZED VIEW ", "CREATE MATERIALIZED VIEW IF NOT EXISTS ", 1)
	return ddl
}

func withSemicolon(sql string) string {
	s := strings.TrimSpace(sql)
	if s == "" || strings.HasSuffix(s, ";") {
		return s
	}
	return s + ";"
}
