version: "2"

linters:
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
