name: Hadolint

on:
  push:
    branches: ["main"]
    paths:
      - "**/Dockerfile"
      - ".github/workflows/hadolint.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Dockerfile"
      - ".github/workflows/hadolint.yml"
  schedule:
    - cron: "15 7 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run hadolint backend dockerfile
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: backend/Dockerfile
          format: sarif
          output-file: hadolint-backend.sarif
          failure-threshold: error

      - name: Run hadolint frontend dockerfile
        if: always()
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: frontend/Dockerfile
          format: sarif
          output-file: hadolint-frontend.sarif
          failure-threshold: error

      - name: Run hadolint stats-collector dockerfile
        if: always()
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: stats-collector/Dockerfile
          format: sarif
          output-file: hadolint-stats-collector.sarif
          failure-threshold: error

      - name: Upload backend analysis results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-backend.sarif
          category: hadolint-backend
          wait-for-processing: true

      - name: Upload frontend analysis results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-frontend.sarif
          category: hadolint-frontend
          wait-for-processing: true

      - name: Upload stats-collector analysis results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-stats-collector.sarif
          category: hadolint-stats-collector
          wait-for-processing: true
